# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1059, 697)
        self.train_button = QtWidgets.QPushButton(Form)
        self.train_button.setGeometry(QtCore.QRect(30, 200, 151, 81))
        self.train_button.setObjectName("train_button")
        self.split_button = QtWidgets.QPushButton(Form)
        self.split_button.setGeometry(QtCore.QRect(30, 100, 151, 71))
        self.split_button.setObjectName("split_button")
        self.run_button = QtWidgets.QPushButton(Form)
        self.run_button.setGeometry(QtCore.QRect(30, 320, 151, 81))
        self.run_button.setObjectName("run_button")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(450, 610, 411, 51))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.output_res = QtWidgets.QTextBrowser(Form)
        self.output_res.setGeometry(QtCore.QRect(210, 100, 401, 461))
        self.output_res.setObjectName("output_res")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(370, 70, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(770, 70, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(590, 570, 91, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(621, 104, 411, 451))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.train_button.setText(_translate("Form", "训练模型"))
        self.split_button.setText(_translate("Form", "划分数据集"))
        self.run_button.setText(_translate("Form", "选择文件并进行预测"))
        self.label.setText(_translate("Form", "结果输出"))
        self.label_2.setText(_translate("Form", "图片预览"))
        self.label_3.setText(_translate("Form", "训练进度"))
